export const GITHUB_WORKFLOW_VERSION = "2"

export function prepareGithubEnvironment(env: Record<string, string | undefined>, review: boolean) {
  const stale =
    env.GITHUB_ACTIONS === "true" &&
    (env.VECTOR_WORKFLOW_VERSION !== GITHUB_WORKFLOW_VERSION || (review && !env.VECTOR_CONFIG_CONTENT))
  if (review) {
    env.VECTOR_PURE = "1"
    env.VECTOR_DISABLE_PROJECT_CONFIG = "1"
    env.VECTOR_CONFIG_CONTENT ??= '{"lsp":false,"formatter":false,"snapshot":false}'
  }
  if (stale) return "This workflow was generated by an older Vector. Run vector github install to update it."
}
