import { GITHUB_WORKFLOW_VERSION } from "@vectordevai/core/review/workflow"
import { PublicSession } from "@vectordevai/schema/public-session"

export function prepareGithubEnvironment(env: Record<string, string | undefined>, review: boolean) {
  const stale =
    env.GITHUB_ACTIONS === "true" &&
    (env.VECTOR_WORKFLOW_VERSION !== GITHUB_WORKFLOW_VERSION || (review && !env.VECTOR_CONFIG_CONTENT))
  const app = env.USE_GITHUB_TOKEN !== "true" && ["auto", "app"].includes(env.VECTOR_GITHUB_AUTH ?? "")
  if (review || app) {
    env.VECTOR_PURE = "1"
    env.VECTOR_DISABLE_PROJECT_CONFIG = "1"
  }
  if (review) {
    env.VECTOR_CONFIG_CONTENT ??= '{"lsp":false,"formatter":false,"snapshot":false}'
  }
  if (stale) return "This workflow was generated by an older Vector. Run vector github install to update it."
}

/** Only an explicit current workflow acknowledgment authorizes public publishing. */
export function githubShareConsent(env: Record<string, string | undefined>): PublicSession.Consent | undefined {
  if (env.SHARE !== "true" || env.VECTOR_SHARE_CONSENT !== String(PublicSession.CONSENT_VERSION)) return
  if (!env.VECTOR_CLI_TOKEN?.startsWith("vct_"))
    throw new Error(
      "Session sharing needs the repository secret VECTOR_CLI_TOKEN. Create one at https://vectordev.ai/auth/cli.",
    )
  return { version: PublicSession.CONSENT_VERSION, public: true, updates: true }
}
