// The workflow `vector github install` writes (section 2.1) and the route job's script (section 2.2). Pure, so the
// tests can parse the YAML and run the script.

import release from "../../../../desktop/package.json"
import { GITHUB_WORKFLOW_VERSION } from "./github.environment"
import { DEFAULT_MENTIONS, parseReviewCommand } from "@vectordevai/core/review/command"
import { PAUSED_LABEL } from "@vectordevai/core/review/skip"

export const WORKFLOW_FILE = ".github/workflows/vector.yml"
export const CLI_PACKAGE = "@vectordevai/cli"

export interface WorkflowOptions {
  provider: string
  model: string
  keys: readonly string[] // the provider's key variables, passed through from same-named repository secrets
  autoReview: boolean
  monthlyUsd?: number // REVIEW_MAX_COST_USD_PER_MONTH; written for paid models only
  version: string // the CLI version to pin
  mentions?: readonly string[] // baked into the route job; Vectorscope mentions and legacy aliases by default
}

// Development builds use the desktop release version instead of a moving registry tag.
export function cliVersionSpec(version: string): { spec: string; pinned: boolean } {
  const pinned = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?$/.test(version) && !version.startsWith("0.0.0")
  return { spec: pinned ? version : release.version, pinned: true }
}

// The route job's script for actions/github-script. It embeds core's parser, so the route job and the CLI can never
// disagree about what a comment asks for.
export function buildRouteScript(mentions: readonly string[] = DEFAULT_MENTIONS): string {
  const script = [
    "// Generated by `vector github install` from parseReviewCommand. Do not edit by hand.",
    `const parseReviewCommand = ${parseReviewCommand.toString()}`,
    `const mentions = ${JSON.stringify(mentions)}`,
    `const PAUSED = ${JSON.stringify(PAUSED_LABEL)}`,
    'const WRITERS = ["admin", "maintain", "write"]',
    "const { owner, repo } = context.repo",
    "const payload = context.payload",
    "",
    "function output(kind, pr, ref) {",
    '  core.setOutput("kind", kind)',
    '  core.setOutput("pr", pr ? String(pr) : "")',
    '  core.setOutput("ref", ref || "")',
    '  core.info("kind=" + kind + " pr=" + (pr || "") + " ref=" + (ref || ""))',
    "}",
    "",
    "// A fork's code is never checked out: its review starts from the merge-base and reads the pull request's",
    "// files from git objects.",
    "async function resolveRef(pr) {",
    "  const { data: pull } = await github.rest.pulls.get({ owner, repo, pull_number: pr })",
    "  if (pull.head.repo && pull.head.repo.full_name === pull.base.repo.full_name) return pull.head.sha",
    "  try {",
    "    const { data } = await github.rest.repos.compareCommitsWithBasehead({",
    "      owner,",
    "      repo,",
    '      basehead: pull.base.sha + "..." + pull.head.sha,',
    "      per_page: 1,",
    "    })",
    "    if (data.merge_base_commit && data.merge_base_commit.sha) return data.merge_base_commit.sha",
    "  } catch (error) {",
    '    core.warning("compare failed (" + (error.status || error.message) + "); starting from the base commit")',
    "  }",
    "  return pull.base.sha",
    "}",
    "",
    'if (context.eventName === "workflow_dispatch") {',
    "  const pr = Number(payload.inputs && payload.inputs.pr)",
    "  if (!Number.isInteger(pr) || pr < 1) {",
    '    core.setFailed("inputs.pr must be a pull request number")',
    '    return output("none")',
    "  }",
    '  return output("review", pr, await resolveRef(pr))',
    "}",
    "",
    "const comment = payload.comment",
    'if (!comment || (comment.user && comment.user.type === "Bot")) return output("none")',
    'const reviewComment = context.eventName === "pull_request_review_comment"',
    "const number = reviewComment ? payload.pull_request.number : payload.issue.number",
    'const kind = parseReviewCommand(comment.body || "", mentions).kind',
    'if (kind === "none" || kind === "dismiss") return output("none")',
    "// A review verb on an issue that is not a pull request does nothing; a task works on issues too.",
    'if (kind !== "task" && !reviewComment && !payload.issue.pull_request) return output("none")',
    "",
    "function react(content) {",
    "  const target = { owner, repo, comment_id: comment.id, content }",
    "  return reviewComment",
    "    ? github.rest.reactions.createForPullRequestReviewComment(target)",
    "    : github.rest.reactions.createForIssueComment(target)",
    "}",
    "",
    "// Only people with write access get a runner, for a task as for a review, so nobody else can start the task job",
    "// or take a writer's place in its queue. Any error counts as no.",
    "let writer = false",
    "try {",
    "  const { data } = await github.rest.repos.getCollaboratorPermissionLevel({ owner, repo, username: comment.user.login })",
    "  writer = WRITERS.includes(data.role_name) || WRITERS.includes(data.permission)",
    "} catch (error) {",
    '  core.warning("permission check failed for " + comment.user.login + ": " + (error.status || error.message))',
    "}",
    "if (!writer) {",
    '  await react("confused").catch(() => {})',
    '  return output("none")',
    "}",
    'if (kind === "task") return output("task", number)',
    'if (kind === "pause") {',
    "  await github.rest.issues.addLabels({ owner, repo, issue_number: number, labels: [PAUSED] })",
    '  await react("+1")',
    '  return output("none")',
    "}",
    'if (kind === "resume") {',
    "  try {",
    "    await github.rest.issues.removeLabel({ owner, repo, issue_number: number, name: PAUSED })",
    "  } catch (error) {",
    "    if (error.status !== 404) throw error",
    "  }",
    '  await react("+1")',
    '  return output("none")',
    "}",
    "return output(kind, number, await resolveRef(number))",
  ].join("\n")
  // Actions evaluates `${{ … }}` anywhere in `with:`, so the script must never contain one.
  if (script.includes("${{")) throw new Error("The route script contains an Actions expression")
  return script
}

export function buildWorkflowYaml(opts: WorkflowOptions): string {
  const auto = opts.autoReview
  const mentions = opts.mentions?.length ? opts.mentions : DEFAULT_MENTIONS
  const cli = cliVersionSpec(opts.version)
  const install = cli.pinned
    ? `npm install -g ${CLI_PACKAGE}@${cli.spec} --prefer-offline --no-audit --no-fund`
    : `npm install -g ${CLI_PACKAGE}@latest --no-audit --no-fund`
  // Shared free models authenticate with VECTOR_CLI_TOKEN, already present in every job.
  const keys =
    opts.provider === "vector"
      ? []
      : [
          "          # Add the selected provider's credentials as repository secrets.",
          ...opts.keys.map((key) => `          ${key}: \${{ secrets.${key} }}`),
          ...["ANTHROPIC_API_KEY", "OPENAI_API_KEY"]
            .filter((key) => !opts.keys.includes(key))
            .map((key) => `          # ${key}: \${{ secrets.${key} }}`),
        ]
  const mentioned = mentions.map((mention) => `contains(github.event.comment.body, '${mention}')`).join(" || ")
  const script = buildRouteScript(mentions)
    .split("\n")
    .map((line) => (line ? `            ${line}` : ""))
    .join("\n")

  const lines = [
    "name: vector",
    "",
    "on:",
    ...(auto ? ["  pull_request:", "    types: [opened, synchronize, reopened, ready_for_review]"] : []),
    "  issue_comment:",
    "    types: [created]",
    "  pull_request_review_comment:",
    "    types: [created]",
    "  workflow_dispatch:",
    "    inputs:",
    "      pr:",
    "        description: Pull request number to review",
    "        required: true",
    "",
    "jobs:",
    "  # Decides who gets a runner. No checkout, and no share of the review queue.",
    "  route:",
    "    if: >-",
    "      github.event_name == 'workflow_dispatch' ||",
    "      ((github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment') &&",
    "        github.event.comment.user.type != 'Bot' &&",
    `        (${mentioned}))`,
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 3",
    "    permissions:",
    "      contents: read",
    "      pull-requests: write",
    "      issues: write",
    "    outputs:",
    "      kind: ${{ steps.route.outputs.kind }}",
    "      pr: ${{ steps.route.outputs.pr }}",
    "      ref: ${{ steps.route.outputs.ref }}",
    "    steps:",
    "      - id: route",
    "        uses: actions/github-script@v7",
    "        with:",
    "          script: |",
    script,
    "",
    "  review:",
    "    needs: route",
    "    if: >-",
    "      !cancelled() && (",
    ...(auto
      ? [
          "        (github.event_name == 'pull_request' &&",
          "          github.event.pull_request.head.repo.full_name == github.repository &&",
          "          github.event.pull_request.draft == false &&",
          "          !contains(github.event.pull_request.labels.*.name, 'vector:skip') &&",
          "          !contains(github.event.pull_request.labels.*.name, 'vector:paused') &&",
          "          github.event.pull_request.user.login != 'dependabot[bot]' &&",
          "          github.event.pull_request.user.login != 'renovate[bot]') ||",
        ]
      : []),
    "        needs.route.outputs.kind == 'review' || needs.route.outputs.kind == 'review-full')",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 20",
    "    concurrency:",
    "      group: vector-review-${{ github.event.pull_request.number || needs.route.outputs.pr }}",
    "      cancel-in-progress: false # queue, never cancel; a newer push replaces a queued run",
    "    permissions:",
    "      contents: read",
    "      pull-requests: write",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          # The route job's ref wins: on a fork it is the merge-base, never the fork's head.",
    "          ref: ${{ needs.route.outputs.ref || github.event.pull_request.head.sha }}",
    "          fetch-depth: 1 # the CLI fetches exactly the commits it needs, only if a review runs",
    "          persist-credentials: false",
    "      - uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 20",
    "      - uses: actions/cache@v4",
    "        with:",
    "          path: ~/.npm",
    `          key: vector-cli-${cli.spec}-\${{ runner.os }}`,
    "      - name: Install Vector",
    `        run: ${install}`,
    "      - name: Review",
    "        run: vector github review",
    "        env:",
    `          VECTOR_WORKFLOW_VERSION: "${GITHUB_WORKFLOW_VERSION}"`,
    "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
    "          VECTOR_CLI_TOKEN: ${{ secrets.VECTOR_CLI_TOKEN }}",
    "          VECTOR_REVIEW_PR: ${{ github.event.pull_request.number || needs.route.outputs.pr }}",
    "          VECTOR_REVIEW_REF: ${{ needs.route.outputs.ref || github.event.pull_request.head.sha }}",
    `          MODEL: ${opts.provider}/${opts.model}`,
    ...(auto ? ["          # REVIEW_AUTO_MODEL: provider/cheaper-model # automatic reviews only"] : []),
    ...(opts.monthlyUsd !== undefined
      ? [`          REVIEW_MAX_COST_USD_PER_MONTH: "${formatAmount(opts.monthlyUsd)}" # "0" means no limit`]
      : []),
    '          VECTOR_PURE: "1"',
    '          VECTOR_DISABLE_PROJECT_CONFIG: "1"',
    `          VECTOR_CONFIG_CONTENT: '{"lsp":false,"formatter":false,"snapshot":false}'`,
    ...keys,
    "",
    "  vector:",
    "    needs: route",
    "    if: needs.route.outputs.kind == 'task'",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 45",
    "    concurrency:",
    "      # One group per comment: GitHub keeps one queued run per group, so a shared group would drop tasks.",
    "      group: vector-${{ needs.route.outputs.pr }}-${{ github.event.comment.id || github.run_id }}",
    "      cancel-in-progress: false",
    "    permissions:",
    "      contents: write",
    "      pull-requests: write",
    "      issues: write",
    ...(auto ? ["      actions: write # dispatches reviews of pull requests Vector opens"] : []),
    "    steps:",
    "      - name: Checkout repository",
    "        uses: actions/checkout@v4",
    "        with:",
    "          fetch-depth: 0",
    "",
    "      - name: Set up Node.js",
    "        uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 20",
    "",
    "      - uses: actions/cache@v4",
    "        with:",
    "          path: ~/.npm",
    `          key: vector-cli-${cli.spec}-\${{ runner.os }}`,
    "      - name: Install Vector",
    `        run: ${install}`,
    "",
    "      - name: Run Vector",
    "        run: vector github run",
    "        env:",
    `          VECTOR_WORKFLOW_VERSION: "${GITHUB_WORKFLOW_VERSION}"`,
    "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
    "          VECTOR_CLI_TOKEN: ${{ secrets.VECTOR_CLI_TOKEN }}",
    '          USE_GITHUB_TOKEN: "true"',
    `          MODEL: ${opts.provider}/${opts.model}`,
    ...(auto ? ['          VECTOR_REVIEW_AUTO: "1"'] : []),
    ...keys,
    "",
  ]
  return lines.join("\n")
}

function formatAmount(value: number): string {
  return Number.isInteger(value) ? String(value) : String(Math.round(value * 100) / 100)
}
